---
title: "**Publications**"
---

::: {style="font-weight:300; text-align:justify; margin-bottom: 1.5em;"}
For a full list of my publications, feel free to explore my [**Google Scholar profile**](https://scholar.google.com/citations?user=kUXXu4IAAAAJ&hl=en&oi=ao). Below are some of my selected publications.
:::

::: pub-card
**Pechlivanis N.**, Karakatsoulis G., Kyritsis K. et al. *Microbial co-occurrence network demonstrates spatial and climatic trends for global soil diversity.*

::: pub-meta
Scientific Data · 2024 · doi: [10.1038/s41597-024-03528-1](https://doi.org/10.1038/s41597-024-03528-1)
:::
:::

::: pub-card
Vlachonikola E., **Pechlivanis N.**, Karakatsoulis G. et al. *T cell receptor gene repertoire profiles in subgroups of patients with chronic lymphocytic leukemia bearing distinct genomic aberrations.*

::: pub-meta
Frontiers in Oncology · 2023 · doi: [10.3389/fonc.2023.1097942](https://doi.org/10.3389/fonc.2023.1097942)
:::
:::

::: pub-card
**Pechlivanis, N.**, Tsagiopoulou, M., Maniou, M.C. et al. *Detecting SARS-CoV-2 lineages and mutational load in municipal wastewater and a use-case in the metropolitan area of Thessaloniki, Greece.* 

::: pub-meta
Scientific Reports · 2022 · doi: [10.1038/s41598-022-06625-6](https://doi.org/10.1038/s41598-022-06625-6)
:::
:::
